
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShipmentProducts
{

using System;
    using System.Collections.Generic;
    
public partial class Contract_LOT
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contract_LOT()
    {

        this.Ct_OperLog = new HashSet<Ct_OperLog>();

    }


    public int ID { get; set; }

    public string LOTCode { get; set; }

    public int ModelID { get; set; }

    public string Specification { get; set; }

    public string FullLOTCode { get; set; }

    public int LiterIndex { get; set; }

    public int BoxCapacity { get; set; }

    public int PalletCapacity { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool CheckFormatSN_SMT { get; set; }

    public bool CheckFormatSN_FAS { get; set; }

    public string SMTNumberFormat { get; set; }

    public bool SMTRangeChecked { get; set; }

    public Nullable<int> SMTStartRange { get; set; }

    public Nullable<int> SMTEndRange { get; set; }

    public string FASNumberFormat { get; set; }

    public bool FASRangeChecked { get; set; }

    public Nullable<int> FASStartRange { get; set; }

    public Nullable<int> FASEndRange { get; set; }

    public bool IsActive { get; set; }

    public Nullable<bool> SingleSN { get; set; }

    public Nullable<byte> PreRackStage { get; set; }

    public Nullable<bool> ParseLog { get; set; }

    public string StepSequence { get; set; }

    public Nullable<bool> HexFasSN { get; set; }

    public Nullable<int> СustomersID { get; set; }

    public Nullable<int> LOTSize { get; set; }

    public Nullable<int> LOT_Shipped { get; set; }

    public string FASNumberFormat2 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ct_OperLog> Ct_OperLog { get; set; }

}

}
