
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShipmentProducts
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Start
{

    public int SerialNumber { get; set; }

    public int PCBID { get; set; }

    public byte LineID { get; set; }

    public string FullSTBSN { get; set; }

    public System.DateTime ManufDate { get; set; }

    public Nullable<System.DateTime> AssemblyDate { get; set; }

    public Nullable<short> AssemblyByID { get; set; }

    public Nullable<short> PrintStationID { get; set; }



    public virtual FAS_SerialNumbers FAS_SerialNumbers { get; set; }

    public virtual FAS_Users FAS_Users { get; set; }

}

}
