
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShipmentProducts
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Shipped_Report
{

    public int ID { get; set; }

    public int ShippedID { get; set; }

    public short Number { get; set; }

    public System.DateTime Date { get; set; }



    public virtual FAS_Shipped_Table FAS_Shipped_Table { get; set; }

}

}
