
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShipmentProducts
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_SerialNumbers
{

    public int SerialNumber { get; set; }

    public Nullable<short> LOTID { get; set; }

    public Nullable<bool> IsUsed { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<bool> IsUploaded { get; set; }

    public Nullable<bool> IsWeighted { get; set; }

    public Nullable<bool> IsPacked { get; set; }

    public Nullable<bool> InRepair { get; set; }

    public Nullable<short> PrintStationID { get; set; }

    public Nullable<int> FixedID { get; set; }

    public Nullable<short> ShipedStatus { get; set; }

    public Nullable<System.DateTime> FixedRange { get; set; }

    public Nullable<int> BlockedPart { get; set; }



    public virtual FAS_PackingGS FAS_PackingGS { get; set; }

    public virtual FAS_Start FAS_Start { get; set; }

}

}
