

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShipmentProducts
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FASEntities : DbContext
{
    public FASEntities()
        : base("name=FASEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Contract_LOT> Contract_LOT { get; set; }

    public virtual DbSet<FAS_GS_LOTs> FAS_GS_LOTs { get; set; }

    public virtual DbSet<FAS_OperationLog> FAS_OperationLog { get; set; }

    public virtual DbSet<FAS_PackingGS> FAS_PackingGS { get; set; }

    public virtual DbSet<Ct_OperLog> Ct_OperLog { get; set; }

    public virtual DbSet<FAS_Models> FAS_Models { get; set; }

    public virtual DbSet<FAS_SerialNumbers> FAS_SerialNumbers { get; set; }

    public virtual DbSet<FAS_Start> FAS_Start { get; set; }

    public virtual DbSet<FAS_Shipped_Table> FAS_Shipped_Table { get; set; }

    public virtual DbSet<CT_Сustomers> CT_Сustomers { get; set; }

    public virtual DbSet<FAS_Shipped_Status_TB> FAS_Shipped_Status_TB { get; set; }

    public virtual DbSet<FAS_Liter> FAS_Liter { get; set; }

    public virtual DbSet<FAS_Users> FAS_Users { get; set; }

    public virtual DbSet<FAS_Shipped_Report> FAS_Shipped_Report { get; set; }

}

}

